#!/bin/sh
# APPLE LOCAL file sdk support

DESTDIR="${1-/tmp/root}"
TARGETS="${2-powerpc i686}"
COMPVERS="4.0.1 `gcc-4.2 -dumpversion`"
OS_VER="`uname -r | sed 's/\..*//'`"

# for debugging
# set -x

# Catch all errors
set -e

rm -rf "$DESTDIR/Developer/SDKs"
rm -rf "$DESTDIR/usr"

do_link() {
  mkdir -p "${2%/*}"
  ln -s "$1" "$2"
}

not_dir() {
  [ ! -d "$1" -o -L "$1" ]
}

dittoln() {
    ditto "$1" "$2"
    (
	cd "$1"
	find . -type f -exec ln -f "$2/{}" \{\} \;
    )
}

for sdk in 10.4u 10.4.0.Internal 10.5 10.5.Internal 10.6 10.6.Internal ; do
  DIR=$DESTDIR/Developer/SDKs/MacOSX$sdk.sdk

  ditto /usr/lib/gcc $DIR/usr/lib/gcc

  # temp to run fixincludes
  ln -s /usr/libexec $DIR/usr/libexec

  for VERS in $COMPVERS; do
    MAJ_VERS="${VERS%*.*}"
    for t in $TARGETS; do
      case "$VERS:$t:$sdk" in
	  4.[2-9].*:*:10.4.*) continue;;
	  4.[2-9].*:*:10.4u.*) continue;;
      esac
      echo "Doing $t fixincludes"
      BASE=/Developer/SDKs/MacOSX$sdk.sdk
      # The current OS build root doesn't have the current OS SDK.
      BASE=${BASE#/Developer/SDKs/MacOSX10.6.sdk}
      BASE=${BASE#/Developer/SDKs/MacOSX10.6.Internal.sdk}
      /usr/libexec/gcc/$t-apple-darwin$OS_VER/$VERS/install-tools/mkheaders -v -v -v $DIR/usr $BASE

      # Remove extraneous directories left by fixincludes
      rm -rf $DIR/usr/lib/gcc/$t-apple-darwin$OS_VER/$VERS/include/c++
      rm -rf $DIR/usr/lib/gcc/$t-apple-darwin$OS_VER/$VERS/include/gcc

      # We don't need to regenerate, and besides, running them the normal
      # way would alter the system headers by default, we avoid that by
      # not giving them the rope.
      rm -rf $DIR/usr/lib/gcc/$t-apple-darwin$OS_VER/$VERS/install-tools

      # fixup ppc_intrinsics.h and stdint.h
      rm -f $DIR/usr/lib/gcc/$t-apple-darwin$OS_VER/$VERS/include/stdint.h
      cp /usr/include/gcc/darwin/$MAJ_VERS/stdint.h \
         $DIR/usr/lib/gcc/$t-apple-darwin$OS_VER/$VERS/include/stdint.h
      rm -f $DIR/usr/lib/gcc/$t-apple-darwin$OS_VER/$VERS/include/ppc_intrinsics.h
      cp /usr/include/gcc/darwin/$MAJ_VERS/ppc_intrinsics.h \
         $DIR/usr/lib/gcc/$t-apple-darwin$OS_VER/$VERS/include/ppc_intrinsics.h

      rm -f $DIR/usr/lib/gcc/$t-apple-darwin$OS_VER/$VERS/libstdc++.dylib
      mkdir -p $DESTDIR/usr/lib/$t-apple-darwin$OS_VER/$VERS
      mkdir -p $DIR/usr/lib/$t-apple-darwin$OS_VER/$VERS
      cp $BASE/usr/lib/libstdc++.6.dylib \
	 $DIR/usr/lib/$t-apple-darwin$OS_VER/$VERS/libstdc++.dylib
      strip -x -c $DIR/usr/lib/$t-apple-darwin$OS_VER/$VERS/libstdc++.dylib || true
    done

    # Add in headers as well
    mkdir -p $DIR/usr/include/gcc/darwin/$MAJ_VERS
    cp /usr/include/gcc/darwin/$MAJ_VERS/stdint.h \
       $DIR/usr/include/gcc/darwin/$MAJ_VERS/stdint.h
    cp /usr/include/gcc/darwin/$MAJ_VERS/ppc_intrinsics.h \
       $DIR/usr/include/gcc/darwin/$MAJ_VERS/ppc_intrinsics.h
    # Copy sym link laid down by gcc_select
    tar -C / -f - -c usr/include/gcc/darwin/default | tar -C $DIR -f - -x
  done

  # we're done with fixincludes, now remove it
  rm $DIR/usr/libexec
done

# Older SDKs don't support 4.2, use 4.0 instead.
for sdk in 10.4u 10.4.0.Internal; do
  DIR=$DESTDIR/Developer/SDKs/MacOSX$sdk.sdk
  mkdir -p $DIR/usr/include/gcc/darwin || exit 1
  rm -f $DIR/usr/include/gcc/darwin/default || exit 1
  ln -s -f 4.0 $DIR/usr/include/gcc/darwin/default || exit 1
done

# from MacOSXSDK10_4
for sdk in 10.4u 10.4.0.Internal; do
  DIR=$DESTDIR/Developer/SDKs/MacOSX${sdk}.sdk
  if not_dir /Developer/SDKs/MacOSX${sdk}.sdk/usr/include/c++/4.0.0/powerpc-apple-darwin$OS_VER; then
    do_link powerpc-apple-darwin8 $DIR/usr/include/c++/4.0.0/powerpc-apple-darwin$OS_VER
    do_link i686-apple-darwin8 $DIR/usr/include/c++/4.0.0/i686-apple-darwin$OS_VER
    do_link ../powerpc64-apple-darwin8 $DIR/usr/include/c++/4.0.0/powerpc-apple-darwin8/ppc64
    do_link ../x86_64-apple-darwin8 $DIR/usr/include/c++/4.0.0/i686-apple-darwin8/x86_64
  else
    do_link ../powerpc64-apple-darwin$OS_VER $DIR/usr/include/c++/4.0.0/powerpc-apple-darwin$OS_VER/ppc64
    do_link ../x86_64-apple-darwin$OS_VER $DIR/usr/include/c++/4.0.0/i686-apple-darwin$OS_VER/x86_64
  fi
done

for sdk in 10.5.Internal ; do
  DIR=$DESTDIR/Developer/SDKs/MacOSX$sdk.sdk

  # 10.5 Didn't have 4.2.1 headers
  mkdir -p $DIR/usr/include/c++ $DIR/usr/include/c++/4.0.0
  ln -s 4.0.0 $DIR/usr/include/c++/4.2.1
  ln -s i686-apple-darwin9 $DIR/usr/include/c++/4.2.1/i686-apple-darwin10
  ln -s powerpc-apple-darwin9 $DIR/usr/include/c++/4.2.1/powerpc-apple-darwin10
done

# Don't do 4.2+ yet...  and trim out all but the 10.5.Internal and 10.6.Internal sdks
for sdk in 10.4u 10.4.0.Internal 10.5 10.6; do
  DIR=$DESTDIR/Developer/SDKs/MacOSX$sdk.sdk
  rm -rf $DIR/usr/lib/{gcc/,}*/4.[2-9].*
  rm -rf $DIR/usr/include/gcc/darwin/4.[2-9]
done
